### ISSUE TITLE
Bert-S的指标

### ISSUE THREAD

**Issue by hecongqing** [yuelinan/Codes-of-EGG#1]
您好，
关于论文中提到Bert-S指标， 我理解应该是BERT-Score F1作为评价指标。
想请问下Bert-S是基于https://github.com/Tiiiger/bert_score计算的吗

**Comment by yuelinan** [comment]
不好意思，回复晚了一些，以下是回答：

是的。我们使用的代码是
from bert_score import score
P, R, F1 = score(predictions_score, references_score, lang="zh", verbose=True)
print(F1.mean())

**Comment by hecongqing** [comment]
感谢
